Webhooks = {
    PLAYER_ACTIONS_LOG = 'https://discord.com/api/webhooks/933474410638213182/RI_X-yGmmwxnDFHumVrD65VyQVME5FoMRXcaMdLd3mrzk9u-mN_27tckALtalx0_z43U',
    PLAYER_EXPLOSION_LOG = 'https://discord.com/api/webhooks/933392712336572466/gKyEqOS_2dZGewWZSyjVTUZgcAMcgdLILxebowrkbhIEvvLIhBYSjul-1unxkCP-WP7v',
    PLAYER_CONNECT_LEAVE_LOG = 'https://discord.com/api/webhooks/933474309622603887/c-71P_ABX4FnlWmoR9LrhbW6Zuxe7Nv1lrQWdB7pstqjk8sfDgCjcNUKQheqqdvkJbyr',
    REQUIRED_SCREENS_LOG = 'https://discord.com/api/webhooks/943918222955126875/IhOn5O_JK8sY3_KPcmoJDPMsLMFdPbL5g6B_7trpumwRwOS4onrb1PNJVj8rY8nWuP9H',
    IMAGE = 'https://cdn.discordapp.com/emojis/889028809955889172.png?size=96',
    BOTNAME = '😈 TORE ANTICHEAT 😈'
}

Admin = {
    GroupBypass = true,
    Groups = {
        ['admin'] = true,
    }
}

ChatAntiFakeMsgs = true
ChatFilterEnable = true
ChatFilters = {
    'www.d0pamine | discord.gg/fjBp55t',
    "www.d0pamine.xyz",
    "d0pamine.xyz",
    "brutanpremium",
    "^1B^2RUT^3A^4N ^5R^6e^7v^8o^9l^1u^2t^3i^5o^4n",
    "BRUTAN",
    'https://discord.gg/hkZgrv3',
    "desudo",
    "You just got fucked mate",
    "Desudo; Plane#0007",
    "FATALITY",
    "cockmenu",
    "FendinX Community",
    "/ooc Credit FendinX ~ https://discord.io/FendinX",
    "Credit FendinX ~ https://discord.io/FendinX",
    "^2Genesis",
    "Genesis Created By: Mihai 'BiCEPS'#5617",
    "hammafia",
    "HamMafia",
    "Anti-LRAC",
    "aries.pl",
    "aries",
    "Aries98",
    "dc.xaries.pl",
    "dezet",
    "Melon#1379",
    "Rena 8",
    "iLostName#7138",
    "Soviet Bear",
    "vjuton.pl",
    "www.renalua.com",
    "34ByTe Community",
    "AlphaV ~ 5391",
    "Baran#8992",
    "lynx",
    'Desudo',
    'Brutan',
    'EulenCheats',
    "Lynx 8",
    "www.lynxmenu.com",
    "HamHaxia",
    "Ham Mafia",
    "www.renalua.com",
    "Fallen#0811",
    "Rena",
    "HamHaxia",
    "Ham Mafia",
    "Xanax#0134",
    ">:D Player Crash",
    "34ByTe Community",
    "lynxmenu.com",
    "Anti-Lynx",
    "Baran#8992",
    "iLostName#7138",
    "Melon#1379",
    "hammafia.com",
    "AlphaV ~ 5391",
    "vjuton.pl",
    "Soviet Bear",
    "MARVIN menu",
    "KoGuSzEk#3251",
    "Xanax#0134",
    ">:D Player Crash",
    "34ByTe Community",
    "lynxmenu.com",
    "Anti-LRAC",
    "Baran#8992",
    "iLostName#7138",
    "Melon#1379",
    "Brutan",
    "EulenCheats",
    "AlphaV ~ 5391",
    "vjuton.pl",
    "Soviet Bear",
    "XARIES",
    "xaries",
    "dc.xaries.pl",
    "aries",
    "aries.pl",
    "Aries98",
    "dezet",
}

FakeTriggersEnable = true
FakeTriggers = {
    'esx_garbagecrew:paycrew',
    'esx-qalle-jail:jailPlayer',
    'esx_communityservice:sendToCommunityService',
    'esx_cargodelivery:sellCargo',
    'esx_pilot:success',
    'esx_taxijob:success',
    'esx_postejob:pay',
    'esx_windowcleaner:GiveItem',
    'esx_windowcleaner:stopVente',
    'esx_windowcleaner:startVente',
    'esx_truckerjob:pay',
    'esx_pizza:pay',
    'esx_tankerjob:pay',
    'esx_mugging:giveMoney',
    'esx_ranger:pay',
    'esx_gopostaljob:pay',
    'esx_banksecurity:pay',
    'esx_slotmachine:sv:2',
    'reanimar:pagamento',
    'offred:salar',
    'esx-qalle-jail:updateJailTime_n96nDDU@X?@zpf8',
    'esx_jailer:sendToJail',
    'esx_jailler:sendToJail',
    'esx-qalle-jail:jailPlayerNew',
    '8321hiue89js',
    'esx_jail:sendToJail',
    'js:jailuser',
    'wyspa_jail:jailPlayer',
    'esx_blanchisseur:startWhitening',
    'whoapd:revive',
    "8321hiue89js",
    "AdminMenu:giveBank",
    "AdminMenu:giveCash",
    "AdminMenu:giveDirtyMoney",
    "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
    "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
    "antilynx8:anticheat",
    "antilynxr4:detect",
    "antilynxr6:detection",
    "ynx8:anticheat",
    "antilynx8r4a:anticheat",
    "lynx8:anticheat",
    "AntiLynxR4:kick",
    "AntiLynxR4:log",
    "Banca:deposit",
    "Banca:withdraw",
    "BsCuff:Cuff696999",
    "CheckHandcuff",
    "cuffServer",
    "cuffGranted",
    "DFWM:adminmenuenable",
    "DFWM:askAwake",
    "DFWM:checkup",
    "DFWM:cleanareaentity",
    "DFWM:cleanareapeds",
    "DFWM:cleanareaveh",
    "DFWM:enable",
    "DFWM:invalid",
    "DFWM:log",
    "DFWM:openmenu",
    "DFWM:spectate",
    "DFWM:ViolationDetected",
    "dmv:success",
    "eden_garage:payhealth",
    "ems:revive",
    "esx_banksecurity:pay",
    "esx_drugs:startHarvestWeed",
    "esx_drugs:startTransformWeed",
    "esx_drugs:startSellWeed",
    "esx_drugs:startHarvestCoke",
    "esx_drugs:startTransformCoke",
    "esx_drugs:startSellCoke",
    "esx_drugs:startHarvestMeth",
    "esx_drugs:startTransformMeth",
    "esx_drugs:startSellMeth",
    "esx_drugs:startHarvestOpium",
    "esx_drugs:startTransformOpium",
    "esx_drugs:startSellOpium",
    "esx_drugs:stopHarvestCoke",
    "esx_drugs:stopTransformCoke",
    "esx_drugs:stopSellCoke",
    "esx_drugs:stopHarvestMeth",
    "esx_drugs:stopTransformMeth",
    "esx_drugs:stopSellMeth",
    "esx_drugs:stopHarvestWeed",
    "esx_drugs:stopTransformWeed",
    "esx_drugs:stopSellWeed",
    "esx_drugs:stopHarvestOpium",
    "esx_drugs:stopTransformOpium",
    "esx_drugs:stopSellOpium",
    "esx:enterpolicecar",
    "esx_fueldelivery:pay",
    "esx_garbagejob:pay",
    "esx_godirtyjob:pay",
    "esx_gopostaljob:pay",
    "esx_handcuffs:cuffing",
    "esx_jail:sendToJail",
    "esx_jail:unjailQuest",
    "esx_jailer:sendToJail",
    "esx_jailer:unjailTime",
    "esx_mecanojob:onNPCJobCompleted",
    "esx_mechanicjob:startHarvest",
    "esx_mechanicjob:startCraft",
    "esx_pizza:pay",
    "esx-qalle-jail:jailPlayer",
    "esx-qalle-jail:jailPlayerNew",
    "esx_ranger:pay",
    "esx_truckerjob:pay",
    "esx_slotmachine:sv:2",
    "hentailover:xdlol",
    "JailUpdate",
    "js:jailuser",
    "js:removejailtime",
    "ljail:jailplayer",
    "esx_vehicleshop:setVehicleOwnedPlayerId",
    "esx_vehicleshop:setVehicleOwnedPlayerId",
    "lscustoms:payGarage",
    "mellotrainer:adminTempBan",
    "mellotrainer:adminKick",
    "mellotrainer:s_adminKill",
    "NB:destituerplayer",
    "NB:recruterplayer",
    "OG_cuffs:cuffCheckNearest",
    "paramedic:revive",
    "unCuffServer",
    "uncuffGranted",
    "vrp_slotmachine:server:2",
    "whoapd:revive",
    "gcPhone:_internalAddMessageDFWM",
    "gcPhone:tchat_channelDFWM",
    "esx_vehicleshop:setVehicleOwnedDFWM",
    "esx_mafiajob:confiscateDFWMPlayerItem",
    "_chat:messageEntDFWMered",
    "lscustoms:pDFWMayGarage",
    "vrp_slotmachDFWMine:server:2",
    "Banca:dDFWMeposit",
    "bank:depDFWMosit",
    "esx_jobs:caDFWMution",
    "esx_fueldDFWMelivery:pay",
    "esx_carthDFWMief:pay",
    "esx_godiDFWMrtyjob:pay",
    "esx_pizza:pDFWMay",
    "esx_ranger:pDFWMay",
    "esx_garbageDFWMjob:pay",
    "esx_truckDFWMerjob:pay",
    "AdminMeDFWMnu:giveBank",
    "AdminMDFWMenu:giveCash",
    "esx_goDFWMpostaljob:pay",
    "esx_baDFWMnksecurity:pay",
    "esx_sloDFWMtmachine:sv:2",
    "esx:giDFWMveInventoryItem",
    "NB:recDFWMruterplayer",
    "esx_biDFWMlling:sendBill",
    "esx_jDFWMailer:sendToJail",
    "esx_jaDFWMil:sendToJail",
    "js:jaDFWMiluser",
    "esx-qalle-jail:jailPDFWMlayer",
    "esx_dmvschool:pDFWMay",
    "LegacyFuel:PayFuDFWMel",
    "OG_cuffs:cuffCheckNeDFWMarest",
    "CheckHandcDFWMuff",
    "cuffSeDFWMrver",
    "cuffGDFWMranted",
    "police:cuffGDFWMranted",
    "esx_handcuffs:cufDFWMfing",
    "esx_policejob:haDFWMndcuff",
    "bank:withdDFWMraw",
    "dmv:succeDFWMss",
    "esx_skin:responseSaDFWMveSkin",
    "esx_dmvschool:addLiceDFWMnse",
    "esx_mechanicjob:starDFWMtCraft",
    "esx_drugs:startHarvestWDFWMeed",
    "esx_drugs:startTransfoDFWMrmWeed",
    "esx_drugs:startSellWeDFWMed",
    "esx_drugs:startHarvestDFWMCoke",
    "esx_drugs:startTransDFWMformCoke",
    "esx_drugs:startSellCDFWMoke",
    "esx_drugs:startHarDFWMvestMeth",
    "esx_drugs:startTDFWMransformMeth",
    "esx_drugs:startSellMDFWMeth",
    "esx_drugs:startHDFWMarvestOpium",
    "esx_drugs:startSellDFWMOpium",
    "esx_drugs:starDFWMtTransformOpium",
    "esx_blanchisDFWMseur:startWhitening",
    "esx_drugs:stopHarvDFWMestCoke",
    "esx_drugs:stopTranDFWMsformCoke",
    "esx_drugs:stopSellDFWMCoke",
    "esx_drugs:stopHarvesDFWMtMeth",
    "esx_drugs:stopTranDFWMsformMeth",
    "esx_drugs:stopSellMDFWMeth",
    "esx_drugs:stopHarDFWMvestWeed",
    "esx_drugs:stopTDFWMransformWeed",
    "esx_drugs:stopSellWDFWMeed",
    "esx_drugs:stopHarvestDFWMOpium",
    "esx_drugs:stopTransDFWMformOpium",
    "esx_drugs:stopSellOpiuDFWMm",
    "esx_society:openBosDFWMsMenu",
    "esx_jobs:caDFWMution",
    "esx_tankerjob:DFWMpay",
    "esx_vehicletrunk:givDFWMeDirty",
    "gambling:speDFWMnd",
    "AdminMenu:giveDirtyMDFWMoney",
    "esx_moneywash:depoDFWMsit",
    "esx_moneywash:witDFWMhdraw",
    "mission:completDFWMed",
    "truckerJob:succeDFWMss",
    "99kr-burglary:addMDFWMoney",
    "esx_jailer:unjailTiDFWMme",
    "esx_ambulancejob:reDFWMvive",
    "esx:getShDFWMaredObjDFWMect",
    "esx_society:getOnlDFWMinePlayers",
    "js:jaDFWMiluser",
    "h:xd",
    "adminmenu:setsalary",
    "adminmenu:cashoutall",
    "bank:tranDFWMsfer",
    "paycheck:bonDFWMus",
    "paycheck:salDFWMary",
    "HCheat:TempDisableDetDFWMection",
    "esx_drugs:pickedUpCDFWMannabis",
    "esx_drugs:processCDFWMannabis",
    "esx-qalle-hunting:DFWMreward",
    "esx-qalle-hunting:seDFWMll",
    "esx_mecanojob:onNPCJobCDFWMompleted",
    "BsCuff:Cuff696DFWM999",
    "veh_SR:CheckMonDFWMeyForVeh",
    "esx_carthief:alertcoDFWMps",
    "mellotrainer:adminTeDFWMmpBan",
    "mellotrainer:adminKickDFWM",
    "esx_society:putVehicleDFWMInGarage",
    "esx_vangelico_robbery:gioielli",
    'give_back',
    'h:xd',
    'HCheat:TempDisableDetDFWMection',
    'hentailover:xdlol',
    'JailUpdate',
    'js:jaDFWMiluser',
    'js:jailuser',
    'js:removejailtime',
    'laundry:washcash',
    'LegacyFuel:PayFuDFWMel',
    'LegacyFuel:PayFuel',
    'ljail:jailplayer',
    'lscustoms:payGarage',
    'lscustoms:pDFWMayGarage',
    'lscustoms:UpdateVeh',
    'lynx8:anticheat',
    'mellotrainer:adminKick',
    'mellotrainer:adminKickDFWM',
    'mellotrainer:adminTeDFWMmpBan',
    'mellotrainer:adminTempBan',
    'mellotrainer:s_adminKill',
    'MF_MobileMeth:RewardPlayers',
    'mission:completDFWMed',
    'mission:completed',
    'NB:destituerplayer',
    'NB:recDFWMruterplayer',
    'NB:recruterplayer',
    'OG_cuffs:cuffCheckNearest',
    'OG_cuffs:cuffCheckNeDFWMarest',
    'paramedic:revive',
    'paycheck:bonDFWMus',
    'paycheck:salary',
    'paycheck:salDFWMary',
    'police:cuffGDFWMranted',
    'police:cuffGranted',
    'program-keycard:hacking',
    'projektsantos:mandathajs',
    'Tem2LPs5Para5dCyjuHm87y2catFkMpV',
    'tost:zgarnijsiano',
    'tostzdrapka:wygranko',
    'truckerJob:succeDFWMss',
    'truckerJob:success',
    'uncuffGranted',
    'unCuffServer',
    'veh_SR:CheckMonDFWMeyForVeh',
    'vrp_slotmachDFWMine:server:2',
    'vrp_slotmachine:server:2',
    'whoapd:revive',
    'wojtek_ubereats:hajs',
    'wojtek_ubereats:napiwek',
    'wyspa_jail:jail',
    'wyspa_jail:jailPlayer',
    'xk3ly-barbasz:getfukingmony',
    'xk3ly-farmer:paycheck',
    'ynx8:anticheat',
    '211ef2f8-f09c-4582-91d8-087ca2130157',
    '265df2d8-421b-4727-b01d-b92fd6503f5e',
    '6a7af019-2b92-4ec2-9435-8fb9bd031c26',
    '8321hiue89js',
    '99kr-burglary:addMDFWMoney',
    'AdminMDFWMenu:giveCash',
    'AdminMeDFWMnu:giveBank',
    'adminmenu:allowall',
    'adminmenu:cashoutall',
    'AdminMenu:giveBank',
    'AdminMenu:giveCash',
    'AdminMenu:giveDirtyMDFWMoney',
    'AdminMenu:giveDirtyMoney',
    'adminmenu:setsalary',
    'advancedFuel:setEssence',
    'antilynx8:anticheat',
    'antilynx8r4a:anticheat',
    'antilynxr4:detect',
    'AntiLynxR4:kick',
    'AntiLynxR4:log',
    'antilynxr6:detection',
    'arisonarp:wiezienie',
    'Banca:dDFWMeposit',
    'Banca:deposit',
    'Banca:withdraw',
    'bank:depDFWMosit',
    'bank:tranDFWMsfer',
    'bank:withdDFWMraw',
    'BsCuff:Cuff696999',
    'BsCuff:Cuff696DFWM999',
    'c65a46c5-5485-4404-bacf-06a106900258',
    'CheckHandcDFWMuff',
    'CheckHandcuff',
    'cuffGDFWMranted',
    'cuffGranted',
    'cuffSeDFWMrver',
    'cuffServer',
    'DFWM:adminmenuenable',
    'DFWM:askAwake',
    'DFWM:checkup',
    'DFWM:cleanareaentity',
    'DFWM:cleanareapeds',
    'DFWM:cleanareaveh',
    'DFWM:enable',
    'DFWM:invalid',
    'DFWM:log',
    'DFWM:openmenu',
    'DFWM:spectate',
    'DFWM:ViolationDetected',
    'DiscordBot:plaDFWMyerDied',
    "SEM_InteractionMenu:Jail",
    "SEM_InteractionMenu:DragNear",
    "SEM_InteractionMenu:GlobalChat",
    "NwmCo",
    'cmg2_animations:sync',
    "esx_inventoryhud:openPlayerInventory",
}

BlacklistedVehiclesEnable = false
BlacklistedVehicles = {
    ['vigilante'] = true,
    ['hydra'] = true,
    ['deluxo'] = true,
    ['freight'] = true,
    ['apc'] = true,
    ['barrage'] = true,
    ['caracara'] = true,
    ['airbus'] = true,
    ['cargoplane'] = true,
    ['chernobog'] = true,
    ['starling'] = true,
    ['savage'] = true,
    ['rhino'] = true,
    ['khanjali'] = true,
}

BlacklistedPedsEnable = true
BlacklistedPeds = {
    ["s_m_y_swat_01"] = true,
    ["a_m_o_acult_01"] = true,
    ["ig_wade"] = true,
    ["s_m_y_hwaycop_01"] = true,
    ["A_M_Y_ACult_01"] = true,
    ['s_m_m_movalien_01'] = true,
    ['s_m_m_movallien_01'] = true,
    ['u_m_y_babyd'] = true,
    ['CS_Orleans'] = true,
    ['A_M_Y_ACult_01'] = true,
    ['S_M_M_MovSpace_01'] = true,
    ['U_M_Y_Zombie_01'] = true,
    ['s_m_y_blackops_01'] = true,
    ['a_f_y_topless_01'] = true,
}

DetectParticles = true
BlockedParticles = {
    [GetHashKey("scr_firework_xmas_burst_rgw")] = true,
    [GetHashKey("exp_grd_petrol_pump")] = true,
    [GetHashKey("scr_clown_bul")] = true,
    [GetHashKey("scr_mich4_firework_trailburst_spawn")] = true,
    [GetHashKey("blood_shark_attack")] = true,
    [GetHashKey("td_blood_shotgun")] = true,
    [GetHashKey("td_blood_throat")] = true,
    [GetHashKey("blood_melee_punch")] = true,
    [GetHashKey("blood_exit")] = true,
    [GetHashKey("blood_chopper")] = true,
    [GetHashKey("trail_splash_blood")] = true,
    [GetHashKey("td_blood_stab")] = true,
    [GetHashKey("td_blood_throat")] = true,
    [GetHashKey("blood_armour_heavy")] = true,
    [GetHashKey("blood_mist")] = true,
    [GetHashKey("blood_nose")] = true,
    [GetHashKey("blood_entry_head_sniper")] = true,
    [GetHashKey("scr_ba_bomb_destroy")] = true,
    [GetHashKey("scr_clown_appears")] = true,
    [GetHashKey("ent_sht_flame")] = true,
    [GetHashKey("scr_indep_firework_trailburst")] = true,
    [GetHashKey("scr_ex1_plane_exp_sp")] = true,
    [GetHashKey("scr_clown_appears")] = true,
    [GetHashKey("scr_indep_firework_trailburst")] = true,
    [GetHashKey("scr_firework_indep_ring_burst_rwb")] = true,
    [GetHashKey("scr_fbi_dd_breach_smoke")] = true,
    [GetHashKey("scr_alien_teleport")] = true,
    [GetHashKey("scr_ex1_plane_exp_sp")] = true,
}

DetectParticleAssets = true
BlockedParticleAssets = {
    -- [GetHashKey("core")] = true,
    [GetHashKey("scr_ba_bomb")] = true,
    [GetHashKey("scr_agencyheist")] = true,
    [GetHashKey("scr_exile1")] = true,
    [GetHashKey("scr_rcbarry1")] = true,
    [GetHashKey("scr_rcbarry2")] = true,
    [GetHashKey("scr_rcpaparazzo1")] = true,
    [GetHashKey("scr_indep_fireworks")] = true,
    [GetHashKey("proj_indep_firework_v2")] = true,
    [GetHashKey("scr_exile1")] = true,
}

DetectExplosions = true
CheaterExplosions = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [38] = true,
    [36] = true,
}

PlayerExplosions = {
    [6] = true,
    [8] = true,
    [7] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [16] = true,
    [17] = true,
    [18] = true,
    [19] = true,
    [21] = true,
    [23] = true,
    [24] = true,
    [25] = true,
    [26] = true,
    [27] = true,
    [28] = true,
    [29] = true,
    [30] = true,
    [31] = true,
    [32] = true,
    [33] = true,
    [34] = true,
    [35] = true,
    [37] = true,
    [39] = true,
    [40] = true,
    [41] = true,
    [42] = true,
    [43] = true,
    [44] = true,
    [45] = true,
    [46] = true,
    [47] = true,
    [48] = true,
    [49] = true,
    [50] = true,
    [51] = true,
    [52] = true,
    [53] = true,
    [54] = true,
    [55] = true,
    [56] = true,
    [57] = true,
    [58] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [63] = true,
    [64] = true,
    [65] = true,
    [66] = true,
    [67] = true,
    [68] = true,
    [69] = true,
    [70] = true,
    [71] = true,
    [72] = true,
}

MaximumProps = 20
BlacklistedObjectsEnable = true
BlacklistedObjects = {
    [-1404869155] = true,
    [GetHashKey('stt_prop_stunt_track_start')] = true,
    [GetHashKey('prop_cs_dildo_01')] = true,
    [GetHashKey('prop_jetski_ramp_01')] = true,
    [GetHashKey('p_spinning_anus_s')] = true,
    [GetHashKey('prop_fnclink_03gate5')] = true,
    [GetHashKey('prop_const_fence03b_cr')] = true,
    [GetHashKey('prop_juicestand')] = true,
    [GetHashKey('apa_prop_flag_uk_yt')] = true,
    [GetHashKey('apa_prop_flag_us_yt')] = true,
    [GetHashKey('apa_prop_flag_mexico_yt')] = true,
    [GetHashKey('prop_windmill_01_l1')] = true,
    [GetHashKey('prop_beach_fire')] = false,
    [GetHashKey('prop_tv_03')] = true,
    [GetHashKey('prop_alien_egg_01')] = true,
    [GetHashKey('prop_cs_cardbox_01')] = true,
    [GetHashKey('prop_xmas_tree_int')] = true,
    [GetHashKey('sm_lod_slod2_22')] = true,
    [GetHashKey('ap1_lod_slod4')] = true,
    [GetHashKey('id2_lod_slod4')] = true,
    [GetHashKey('po1_lod_slod4')] = true,
    [GetHashKey('cs4_lod_04_slod2')] = true,
    [GetHashKey('dt1_lod_slod3')] = true,
    [GetHashKey('imp_prop_impexp_half_cut_rack_01b')] = true,
    [GetHashKey('prop_bikini_disp_03')] = true,
    [GetHashKey('p_airdancer_01_s')] = true,
    [GetHashKey('p_crahsed_heli_s')] = true,
    [GetHashKey('prop_beware_dog_sign')] = true,
    [GetHashKey('prop_cs_dog_lead_2a')] = true,
    [GetHashKey('prop_knife')] = true,
    [GetHashKey('sr_prop_stunt_tube_crn_15d_05a')] = true,
    [GetHashKey('ch2_02_obbuilding')] = true,
    [GetHashKey('cs4_lod_01_slod3')] = true,
    [GetHashKey('prop_rub_carwreck_14')] = true,
    [GetHashKey('db_apart_02_')] = true,

    -- PROTOŽE COFFISTER
   --[[ [GetHashKey('bkr_prop_biker_bblock_hump_01')] = true,
    [GetHashKey('csx_coastbigroc03_')] = true,
    [GetHashKey('csx_coastrok3_')] = true,
    [GetHashKey('gr_prop_gr_cnc_01a')] = true,
    [GetHashKey('gr_prop_gr_ramproof_gate')] = true,
    [GetHashKey('gr_prop_gr_target_small_04a')] = true,
    [GetHashKey('gr_prop_gr_target_small_01b')] = true,
    [GetHashKey('cs4_lod_01_slod3')] = true,
    [GetHashKey('hw1_lod_08_09_16_17_18')] = true,
    [GetHashKey('id2_lod_00_ab_slod2')] = true,
    [GetHashKey('dt1_lod_03_04_05_11')] = true,
    [GetHashKey('p_spinning_anus_s')] = true,
]]--
}